### ISSUE TITLE
Supprimer l'autocompletion dans le champs de saisie de la tribune

### ISSUE THREAD

**Issue by koocotte** [sveetch/sveetch-net#12]
Le champ de saisie du message de la tribune propose par défaut de l'autocompletion. Cela n'a pas trop de sens car on saisi rarement deux fois le même message.

Plus gênant, sur les téléphones portables, la liste des anciens messages proposé par l'autocompletion peut facilement prendre tout l'écran lorsqu'on est un utilisateur assidu de la tribune.

L'attribut autocomplete doit permettre de désactiver ce comportement

Sans rapport mais intéressant également, l'attribut autofocus permettrait peut-être que la page scroll directement tout en bas où sont également les messages les plus intéressants. A voir si cela fonctionne. Cela risque de perturber les moules qui sont râleuses de nature.

http://www.w3schools.com/tags/tag_input.asp

**Comment by sveetch** [comment]
You should have posted this on sveetch/django-tribune not sveetch-net (which is only the recipe of my website) but at least you took effort to post an issue :)

**Comment by sveetch** [comment]
Since Chrome refuse to honor `autocomplete` correctly from the specifications, i will use the last trick that should works everywhere (see link's last paragraph):

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Disabling_autocompletion

Added also the `autofocus` attribute, i can't see reason why it would be bad.

Will come in next release.

**Comment by sveetch** [comment]
Done since sveetch/djangotribune@f1beb6a
